version: '3'
services:
  nginx-proxy: 
    image: nginx:1.17-alpine
    container_name: nginx-proxy-local
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    extra_hosts:
      - domain:127.0.0.0